version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker

  fastapi_service:
    build: ./fastapi_service
    ports:
      - "9000:9000"
    env_file:
      - ./fastapi_service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 9000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
