version: "3"
services:
  backend:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn sail_backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - redis
  redis:
    image: redis:alpine
