openapi: 3.0.0
info:
  title: SAIL API
  version: v1
paths:
  /api/v1/ai/chat:
    post:
      summary: DeepSeek AI chat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: AI reply
  /api/v1/search/parse:
    post:
      summary: Semantic query → filters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Parsed filter DSL
